name: NoPVP
api: [4.0.0]
main: M7Dev\NoPVP\Main
author: M7Dev
website: https://github.com/M7Dev
version: 1.0.2

commands:
  nopvp:
    description: NoPVP Command
    permission: np.command.staff
    aliases:
     - np 

permissions:
  np.command.staff:
    default: op
    description: "Allow player to use NoPVP command"
